Appointments/Areas/Admin/Controllers/RoleController.cs
using Appointments.Api.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using X.PagedList;
using Microsoft.AspNet.Identity.Owin;
using Appointments.Api.Areas.Admin.Models;
using System.Net;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Appointments.Api.Areas.Admin.Controllers
{
    [Authorize(Roles = AppRoles.Admin)]
    public class RoleController : Controller
    {
        private ApplicationUserManager _userManager;
        private ApplicationRoleManager _roleManager;
        private int intPageSize = 25;

        // GET: Admin/Role
        public ActionResult Index(int? page)
        {
            int intPage = page ?? 1;

            try {

                //Get Users
                var roles = RoleManager.Roles
                    .OrderBy(x => x.Name)
                    .Select(x => new RoleDTO() {
                        Id = x.Id,
                        RoleName = x.Name
                    });

                ViewBag.Roles = roles.ToPagedList(intPage, intPageSize);
                return View();
            }
            catch (Exception ex) {
                ModelState.AddModelError(string.Empty, "Error: " + ex);
                List<RoleDTO> col_UserDTO = new List<RoleDTO>();
                ViewBag.Roles = col_UserDTO.ToPagedList(1, intPageSize);
                return View();
            }
        }

        // GET: Admin/Role/Add
        public ActionResult Add() {
            RoleDTO role = new RoleDTO();
            return View(role);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(RoleDTO paramRoleDTO) {
            try {
                if (paramRoleDTO == null) {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var RoleName = paramRoleDTO.RoleName.Trim();
                if (string.IsNullOrEmpty(RoleName)) {
                    throw new Exception("No RoleName");
                }
                // Create Role
                if (!RoleManager.RoleExists(RoleName)) {
                    RoleManager.Create(new IdentityRole(RoleName));
                }
                return Redirect("~/Admin/ViewAllRoles");
            }
            catch (Exception ex) {
                ModelState.AddModelError(string.Empty, "Error: " + ex);
                return View();
            }
        }

        // DELETE: /Admin/Role/Delete?roleName=TestRole
        public ActionResult Delete(string roleName) {
            try {
                if (roleName == null) {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                if (roleName.ToLower() == AppRoles.Admin) {
                    throw new Exception(String.Format("Cannot delete {0} Role.", roleName));
                }

                var UsersInRole = RoleManager.FindByName(roleName).Users.Count();
                if (UsersInRole > 0) {
                    throw new Exception(String.Format("Canot delete {0} Role because it still has users.", roleName));
                }
                var objRoleToDelete = (from objRole in RoleManager.Roles
                                       where objRole.Name == roleName
                                       select objRole).FirstOrDefault();
                if (objRoleToDelete != null) {
                    RoleManager.Delete(objRoleToDelete);
                }
                else {
                    throw new Exception(String.Format("Cannot delete {0} Role does not exist.", roleName));
                }
            }
            catch (Exception ex) {
                ModelState.AddModelError(string.Empty, "Error: " + ex);
                
            }

            return RedirectToAction("Index");
        }

        // Utility
        #region public ApplicationUserManager UserManager
        public ApplicationUserManager UserManager {
            get {
                return _userManager ?? Request.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set {
                _userManager = value;
            }
        }
        #endregion
        #region public ApplicationRoleManager RoleManager
        public ApplicationRoleManager RoleManager {
            get {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set {
                _roleManager = value;
            }
        }
        #endregion
    }
}

Appointments/Areas/Admin/Controllers/UserController.cs
using Appointments.Api.Areas.Admin.Models;
using Appointments.Api.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using X.PagedList;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System.Net;
using Appointments.Api.Models;

namespace Appointments.Api.Areas.Admin.Controllers {
    [Authorize(Roles = AppRoles.Admin)]
    public class UserController : Controller {
        private ApplicationUserManager _userManager;
        private ApplicationRoleManager _roleManager;

        #region USER
        // Controllers
        // GET: /User/
        #region public ActionResult Index(string searchStringUserNameOrEmail)
        public ActionResult Index(string searchStringUserNameOrEmail, string currentFilter, int? page) {
            int intPage = 1;
            int intPageSize = 25;

            try {
                if (searchStringUserNameOrEmail != null) {
                    intPage = 1;
                }
                else {
                    if (currentFilter != null) {
                        searchStringUserNameOrEmail = currentFilter;
                        intPage = page ?? 1;
                    }
                    else {
                        searchStringUserNameOrEmail = "";
                        intPage = page ?? 1;
                    }
                }
                ViewBag.CurrentFilter = searchStringUserNameOrEmail;

                //Get Users
                var users = UserManager.Users
                    .Where(x => x.UserName.Contains(searchStringUserNameOrEmail))
                    .OrderBy(x => x.UserName)
                    .Select( x => new ExpandedUserDTO() {
                        UserName = x.UserName,
                        Email = x.Email,
                        PhoneNumber = x.PhoneNumber,
                        LockoutEndDateUtc = x.LockoutEndDateUtc
                    });
                
                ViewBag.ExpandedUsers = users.ToPagedList(intPage, intPageSize);
                return View();
            }
            catch (Exception ex) {
                ModelState.AddModelError(string.Empty, "Error: " + ex);
                List<ExpandedUserDTO> col_UserDTO = new List<ExpandedUserDTO>();
                ViewBag.ExpandedUsers = col_UserDTO.ToPagedList(1, intPageSize);
                return View();
            }
        }
        #endregion

        // GET: /Admin/User/Add
        public ActionResult Add() {
            ExpandedUserDTO objExpandedUserDTO = new ExpandedUserDTO();
            ViewBag.Roles = GetAllRolesAsSelectList();
            return View(objExpandedUserDTO);
        }

        // POST: /Admin/User/Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        #region public ActionResult Add(ExpandedUserDTO paramExpandedUserDTO)
        public ActionResult Add(ExpandedUserDTO paramExpandedUserDTO) {
            try {
                if (paramExpandedUserDTO == null) {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var Email = paramExpandedUserDTO.Email.Trim();
                var UserName = paramExpandedUserDTO.Email.Trim();
                var Password = paramExpandedUserDTO.Password.Trim();
                if (Email == "") {
                    throw new Exception("No Email");
                }
                if (Password == "") {
                    throw new Exception("No Password");
                }
                // UserName is LowerCase of the Email
                UserName = Email.ToLower();
                // Create user
                var objNewAdminUser = new ApplicationUser { UserName = UserName, Email = Email };
                var AdminUserCreateResult = UserManager.Create(objNewAdminUser, Password);
                if (AdminUserCreateResult.Succeeded == true) {
                    string strNewRole = Convert.ToString(Request.Form["Roles"]);
                    if (strNewRole != "0") {
                        // Put user in role
                        UserManager.AddToRole(objNewAdminUser.Id, strNewRole);
                    }
                    return RedirectToAction("Index");
                }
                else {
                    ViewBag.Roles = GetAllRolesAsSelectList();
                    ModelState.AddModelError(string.Empty,
                        "Error: Failed to create the user. Check password requirements.");
                    return View(paramExpandedUserDTO);
                }
            }
            catch (Exception ex) {
                ViewBag.Roles = GetAllRolesAsSelectList();
                ModelState.AddModelError(string.Empty, "Error: " + ex);
                return View();
            }
        }
        #endregion

        // GET: /Admin/User/Edit 
        #region public ActionResult Edit(string userName)
        public ActionResult Edit(string userName) {
            if (userName == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExpandedUserDTO objExpandedUserDTO = GetUser(userName);
            if (objExpandedUserDTO == null) {
                return HttpNotFound();
            }
            return View(objExpandedUserDTO);
        }
        #endregion

        // POST: /Admin/EditUser
        [HttpPost]
        [ValidateAntiForgeryToken]
        #region public ActionResult Edit(ExpandedUserDTO paramExpandedUserDTO)
        public ActionResult Edit(ExpandedUserDTO paramExpandedUserDTO) {
            try {
                if (paramExpandedUserDTO == null) {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                ExpandedUserDTO objExpandedUserDTO = UpdateDTOUser(paramExpandedUserDTO);
                if (objExpandedUserDTO == null) {
                    return HttpNotFound();
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex) {
                ModelState.AddModelError(string.Empty, "Error: " + ex);
                return View("Edit", GetUser(paramExpandedUserDTO.UserName));
            }
        }
        #endregion

        // DELETE: /Admin/User/Delete
        #region public ActionResult Delete(string userName)
        public ActionResult Delete(string userName) {
            try {
                if (userName == null) {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                if (userName.ToLower() == this.User.Identity.Name.ToLower()) {
                    ModelState.AddModelError(
                        string.Empty, "Error: Cannot delete the current user");
                    return View("EditUser");
                }
                ExpandedUserDTO objExpandedUserDTO = GetUser(userName);
                if (objExpandedUserDTO == null) {
                    return HttpNotFound();
                }
                else {
                    DeleteUser(objExpandedUserDTO);
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex) {
                ModelState.AddModelError(string.Empty, "Error: " + ex);
                return View("Edit", GetUser(userName));
            }
        }
        #endregion
        #endregion

        #region USER_ROLES
        // GET: /Admin/User/EditRoles/TestUser 
        #region ActionResult EditRoles(string userName)
        public ActionResult EditRoles(string userName) {
            if (userName == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            userName = userName.ToLower();
            // Check that we have an actual user
            ExpandedUserDTO objExpandedUserDTO = GetUser(userName);
            if (objExpandedUserDTO == null) {
                return HttpNotFound();
            }
            UserAndRolesDTO objUserAndRolesDTO =
                GetUserAndRoles(userName);
            return View(objUserAndRolesDTO);
        }

        // POST: /Admin/User/EditRoles/TestUse
        [HttpPost]
        [ValidateAntiForgeryToken]
        #region public ActionResult EditRoles(UserAndRolesDTO paramUserAndRolesDTO)
        public ActionResult EditRoles(UserAndRolesDTO paramUserAndRolesDTO) {
            try {
                if (paramUserAndRolesDTO == null) {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                string UserName = paramUserAndRolesDTO.UserName;
                string strNewRole = Convert.ToString(Request.Form["AddRole"]);
                if (strNewRole != "No Roles Found") {
                    // Go get the User
                    ApplicationUser user = UserManager.FindByName(UserName);
                    // Put user in role
                    UserManager.AddToRole(user.Id, strNewRole);
                }
                ViewBag.AddRole = new SelectList(RolesUserIsNotIn(UserName));
                UserAndRolesDTO objUserAndRolesDTO =
                    GetUserAndRoles(UserName);
                return View(objUserAndRolesDTO);
            }
            catch (Exception ex) {
                ModelState.AddModelError(string.Empty, "Error: " + ex);
                return View("EditRoles");
            }
        }
        #endregion
        #endregion

        // DELETE: /Admin/User/DeleteRole?userName="TestUser&roleName=Administrator
        #region public ActionResult DeleteRole(string userName, string roleName)
        public ActionResult DeleteRole(string userName, string roleName) {
            try {
                if ((userName == null) || (roleName == null)) {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                userName = userName.ToLower();
                // Check that we have an actual user

Appointments/Areas/Admin/Views/User/Add.cshtml
@model Appointments.Api.Areas.Admin.Models.ExpandedUserDTO
@{
    ViewBag.Title = "Add";
}

<h2>Add User</h2>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class ="text-danger"})

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class="form-control"} })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Roles, htmlAttributes: new { @class = "control-label" })
            @Html.DropDownList("Roles")
        </div>

        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
}

Appointments/Areas/Admin/Views/User/Edit.cshtml
@model Appointments.Api.Areas.Admin.Models.ExpandedUserDTO
@{
    ViewBag.Title = "Edit User";
}

<h2>Add User</h2>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label" })
            @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LockoutEndDateUtc, htmlAttributes: new { @class = "control-label" })
            @Html.DisplayFor(model => model.LockoutEndDateUtc, new { htmlAttributes = new { @class = "form-control" } })
        </div>


        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
            @Html.ActionLink("Edit Roles", "EditRoles", new { userName = Model.UserName }, new { @class = "btn btn-default" })
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
}

Appointments/Areas/Admin/Views/User/EditRoles.cshtml
@model Appointments.Api.Areas.Admin.Models.UserAndRolesDTO
@using Appointments.Api.Utils
@{
    ViewBag.Title = "Edit User Role";
}
<h2>EditRoles</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <br />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div>
        @Html.ActionLink("Back", "Edit", new { UserName = Model.UserName }, new { @class = "btn btn-default" })
        <input type="submit" value="Add Role" class="btn btn-default" />
        @Html.DropDownList("AddRole")
    </div>
    <br />
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Existing Roles</th>
                <th></th>
            </tr>
        </thead>

        @foreach (var item in Model.colUserRoleDTO) {
            <tr>
                <td>@Html.DisplayFor(model => item.RoleName)</td>
                <td>
                    @if (!((Model.UserName.ToLower() == User.Identity.Name.ToLower()) && item.RoleName == AppRoles.Admin) && item.RoleName != "No Roles Found") {
                        @Html.ActionLink("Delete", "DeleteRole", new { userName = item.UserName, roleName = item.RoleName }, new { onclick = "return confirm('Are you sure you wish to delete this role?');" })
                    }
                </td>
            </tr>
        }
    </table>
}

Appointments/Areas/Admin/Views/User/Index.cshtml
@model X.PagedList.IPagedList<Appointments.Api.Areas.Admin.Models.ExpandedUserDTO>
@using X.PagedList.Mvc;
@using X.PagedList;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css"/>
@{
    ViewBag.Title = "Admin";
}

<h2>Users</h2>
<p>
    @Html.ActionLink("Create New", "Add", null, new { @class ="btn btn-default"})
    @Html.ActionLink("Edit Roles", "Index","Role", null, new { @class = "btn btn-default" })
</p>
<br/>

@using(Html.BeginForm("Index","User", FormMethod.Get)) {
    <div class="form-group">
        <label>Search:</label>
        @Html.TextBox("searchStringUserNameOrEmail", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search"/>
    </div>
}
<br/>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Email</th>
            <th>Locked Out</th>
            <th></th>
        </tr>
    </thead>

    @foreach (var item in ViewBag.ExpandedUsers) {
        <tr>
            <td>@item.Email</td>
            <td>@item.LockoutEndDateUtc</td>
            <td>
                @Html.ActionLink("Edit","Edit", new { userName = item.UserName}) |
                @if(item.UserName.ToLower() != this.User.Identity.Name.ToLower()) {
                    @Html.ActionLink("Delete","DeleteUser", new { userName = item.UserName}, new { onclick ="return confirm('Are you sure you wish to delete this user?');" })
                }
            </td>
        </tr>
    }
</table>
@Html.PagedListPager((IPagedList)ViewBag.ExpandedUsers, page => Url.Action("Index", new { page }))